name: deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
        
jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Build and link
        run: make site_build

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          build_dir: site
        env:
          GITHUB_PAT: ${{ secrets.GH_DEPLOY_TOKEN }}
